server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: 'false'
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: managementSystem
  datasource:
    password: Torterra@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: aquiem
    url: jdbc:mysql://localhost:3306/Users
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000
admin:
  password: '"adminPass"'
  username: '"admin"'